# Generated by Django 4.1 on 2022-09-06 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_alter_post_liked_persons_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
