# Generated by Django 4.1 on 2022-08-22 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('referal_code', models.UUIDField(default=uuid.uuid4)),
                ('designation', models.CharField(choices=[('DOC', 'DOCTOR'), ('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
