# Generated by Django 4.1 on 2022-08-25 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='referal_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
