# Generated by Django 4.1 on 2022-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doccertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccertificate',
            name='certi',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
